resources:
- allow-argocd-to-manage.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=e7c9f2780ad3fe595e07c7929e0d1719842da7a3
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: e7c9f2780ad3fe595e07c7929e0d1719842da7a3

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service
