---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/14rcole-rhtap/infra-deployments
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-preview-disable-auto-sync-dev
