apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/14rcole/application-service/config/default?ref=c72856ce0efdccc22a6bd9580ef483cfae08a656
components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/rycole/application-service
    newTag: latest
configMapGenerator:
  - literals:
      - GITHUB_ORG=14rcole-rhtap
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
namespace: application-service
