apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/14rcole/application-service/config/default?ref=c72856ce0efdccc22a6bd9580ef483cfae08a656


components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: 338ad7f4e3577aa7c9b5be293a97689d84a28442

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace


namespace: application-service
