apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=7eb2e4bceee9fa44daa16541bfd0922bcf6d8371
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/rycole/release-service
    newTag: latest
namespace: release-service
