apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=5db32c5df1f47cb546ed6aa02301f19acbac0358
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/rycole/release-service
    newTag: latest
namespace: release-service
components:
  - ../../../argo-cd-apps/k-components/disable-auto-sync
