resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- integration.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: integration-service

configMapGenerator:
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
