kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-integrationtestscenarios
rules:
  - apiGroups:
    - "appstudio.redhat.com"
    resources:
      - "integrationtestscenarios"
    verbs:
      - "create"
      - "get"
      - "list"
      - "patch"
      - "update"
      - "watch"
      - "delete"
      - "deletecollection"
  - apiGroups:
    - "resolution.tekton.dev"
    resources:
      - "resolutionrequests"
    verbs:
      - "create"
      - "get"
      - "list"
      - "delete"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-integrationtestscenarios
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-integrationtestscenarios
