apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/integration-service/config/default?ref=ed11406a2c6708b02c48ded645ac59f2c7fa6bf0
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/rycole/integration-service
    newTag: profiling
namespace: integration-service
components:
  - ../k-components/manager-resources-patch
