resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/14rcole/integration-service/config/default?ref=156bbf67ebc8d6de30219414a41eb17bcf9224e4
  - integration.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/rycole/integration-service
    newTag: stoneintg-600
namespace: integration-service
patches:
  - path: ./manager_resources_patch.yaml
